### PR TITLE
Performance improvements

### PR DESCRIPTION
**Pull request by codejet**
Caching elements, chaining, using "on" for events, removed unnecessary variables from resizeChatArea function. 
Also added semicolon after resizeChatArea declaration.

### CODE REVIEW

**Comment by manuelkiessling** [comment]
Hi @codejet,

thanks for the improvements. You didn't change `$('#input')` to `$input` in https://github.com/ManuelKiessling/bivouac/pull/2/files#L0L44 - is there a specific reason for this?

**Comment by codejet** [comment]
Hey Manuel,

you only need to cache elements when they're going to be used more than once (or it's likely that this is going to happen) to avoid requerying, and you're only using #input once.

**Comment by manuelkiessling** [comment]
True, but I didn't like the idea of using 99% of the elements in one way, and one in another way, thus I changed it.

**Comment by codejet** [comment]
Just as an explanation from my point of view: storing jQuery objects in variables (var $myElem = $('#myElem') - the $ prefix of the variable name is merely a useful convention) and just using the jQuery function are not really two different ways of doing things.

When you are looking for an element in the DOM once, it's perfectly fine to use "$('#myElem')". You don't have to store it in a variable. Especially if you have many elements you're only using once. Otherwise you might end up with a lot of (unnecessary) variables.

But if you have to work with an element several times inside the same scope but without the possibility to use chaining, and you don't store it, jQuery would have to find it in the DOM each time you want to use it (and DOM interaction is a performance bottleneck).

**Pull request merged**
